version: '2'

services:
  web:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3030:3000'
    links:
      - db

  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /data/db
